MtMoon_B2F_Text_MiguelIntro::
    .string "Hey, stop!\p"
    .string "I found these fossils!\n"
    .string "They're both mine!$"

MtMoon_B2F_Text_MiguelDefeat::
    .string "Okay!\n"
    .string "I'll share!$"

MtMoon_B2F_Text_WellEachTakeAFossil::
    .string "We'll each take a fossil!\n"
    .string "No being greedy!$"

MtMoon_B2F_Text_ThenThisFossilIsMine::
    .string "All right.\n"
    .string "Then this fossil is mine!$"

MtMoon_B2F_Text_LabOnCinnabarRegeneratesFossils::
    .string "Far away, on CINNABAR ISLAND,\n"
    .string "there's a POKéMON LAB.\p"
    .string "They do research on regenerating\n"
    .string "fossils.$"

MtMoon_B2F_Text_Grunt1Intro::
	.string "Jessie: Hold up, Twerp! We, TEAM ROCKET,\n"
	.string "shall find the fossils!\p"
	.string "James: When we hand them over to The\n"
	.string "Boss, he'll be able to revive them, and\n"
	.string "earn us huge riches!\p"
	.string "Jessie: You probably don't have any\n"
	.string "good pokemon. So get lost!$"

MtMoon_B2F_Text_Grunt1Defeat::
	.string "What happened? Those pokemon of yours\n"
	.string "were disgustingly strong!$"

MtMoon_B2F_Text_Grunt1PostBattle::
	.string "Jessie: The Boss'll sure be mad with us\n"
	.string "if we come back empty handed.\p"
	.string "James: You know, this kid's pokemon\n"
	.string "seemed really strong. If we swiped them,\n"
	.string "I'm sure the Boss'll be impressed.$"

MtMoon_B2F_Text_Grunt2Intro::
    .string "We, TEAM ROCKET, are POKéMON\n"
    .string "gangsters!\l"
    .string "We strike fear with our strength!$"

MtMoon_B2F_Text_Grunt2Defeat::
    .string "I blew it!$"

MtMoon_B2F_Text_Grunt2PostBattle::
    .string "Darn it all!\n"
    .string "My associates won't stand for this!$"

MtMoon_B2F_Text_Grunt3Intro::
    .string "We're pulling a big job here!\n"
    .string "Get lost, kid!$"

MtMoon_B2F_Text_Grunt3Defeat::
    .string "So, you are good…$"

MtMoon_B2F_Text_Grunt3PostBattle::
    .string "If you find a fossil, give it to me\n"
    .string "and scram!$"

MtMoon_B2F_Text_Grunt4Intro::
    .string "Little kids shouldn't be messing\n"
    .string "around with grown-ups!\p"
    .string "It could be bad news!$"

MtMoon_B2F_Text_Grunt4Defeat::
    .string "I'm steamed!$"

MtMoon_B2F_Text_Grunt4PostBattle::
    .string "POKéMON lived here long before\n"
    .string "people came.$"

MtMoon_B2F_Text_YouWantDomeFossil::
    .string "Do you want the DOME FOSSIL?$"

MtMoon_B2F_Text_YouWantHelixFossil::
    .string "Do you want the HELIX FOSSIL?$"

MtMoon_B2F_Text_ObtainedHelixFossil::
    .string "Obtained the HELIX FOSSIL!$"

MtMoon_B2F_Text_ObtainedDomeFossil::
    .string "Obtained the DOME FOSSIL!$"

